text_slang_detector:
  lora_params:
    alpha: 32
    dropout: 0.1
    r: 16
    target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
  name: Qwen/Qwen2.5-1.5B-Instruct
  output_dir: c:\Users\jiang\Desktop\Projects\Lingo\models\text_models
